// Generated by `dart setup.dart ios` into libclash/ios/ (see project.yml
// HEADER_SEARCH_PATHS). libclash.h declares the Go exports (invokeMethod,
// startTUN, stopTun, ...); bride.h declares the callback function pointers
// the host must install before calling into Go.
#include "libclash.h"
#include "bride.h"
